server:
  port: 8081

mybatis:
  type-aliases-package: com.portfolio.community.dtos
  configuration:
    map-underscore-to-camel-case: true
    level:
      com.study.springboard.repository: trace
    default-enum-type-handler: com.portfolio.community.type.BoardTypeHandler

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio
    username: root
    password: admin!32

  messages:
    basename: messages, errors
    encoding: utf-8

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    devtools:
      livereload:
        enabled: true
      remote:
        restart:
          enabled: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 40MB

file:
  dir: C:\Users\82103\Desktop\upload\
