mybatis:
  type-aliases-package: com.portfolio.community.dtos
  configuration:
    map-underscore-to-camel-case: true
    level:
      com.study.springboard.repository: trace
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.portfolio.community.enums.BoardTypeHandler

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio
    username: root
    password: admin!32

  messages:
    basename: messages
    encoding: utf-8

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    devtools:
      livereload:
        enabled: true
      remote:
        restart:
          enabled: true

jwt:
  secret: wooj123wooj123wooj123wooj

file:
  dir: C:\Users\82103\Desktop\upload\


