mybatis:
  type-aliases-package: com.portfolio.communityuser.dtos
  configuration:
    map-underscore-to-camel-case: true
    level:
      com.study.springboard.repository: trace
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.portfolio.communityuser.enums.BoardTypeHandler

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio
    username: root
    password: admin!32

  messages:
    basename: errors, messages
    encoding: utf-8

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 40MB

jwt:
  secret: wooj123wooj123wooj123wooj

file:
  dir: C:\Users\82103\Desktop\upload\
